### ISSUE TITLE
Temperature Discrepancy Between FGLair and Homekit 

### ISSUE THREAD

**Issue by danhvos** [jonathangreen/homebridge-fglair#3]
**Describe The Bug:**

Fujitu heat pump is set to Cool 75.  Homekit displays "Cool to 74".  
I'm sure this is related to a rounding or converting issue, as I have seen similar issues with Ecobee in the past.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
![20230923_010202000_iOS](https://github.com/jonathangreen/homebridge-fglair/assets/25989419/743e802a-94d5-4b25-a1cb-84902a8483a4)
![20230923_010155000_iOS](https://github.com/jonathangreen/homebridge-fglair/assets/25989419/d709108e-fdb3-4e1e-b598-ffa54aa8af11)

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by danhvos** [comment]
I just installed Eve, and it displays it as 74.5

**Comment by danhvos** [comment]
I just installed Eve, and it displays it as 74.5

**Comment by jonathangreen** [comment]
That is really interesting, it is a conversion / rounding issue for sure. 

I'm in Canada, so my Heatpump and HomeKit are set up for Celsius which displays both the set point and current temperature with a decimal point. 

I should be able to get that sorted out for Fahrenheit though. Can you get a couple of pieces of information for me to help troubleshoot?

In your FGLair app can you click the little button at the top to refresh the current temperature and tell me if it displays a decimal or just a whole number?

It would also be super helpful if you could start Homebridge with debug logging turned on and post a log here so I can see what the raw data from the heat pump looks like when it's configured for Fahrenheit.

**Comment by jonathangreen** [comment]
So I tried putting my app in Fahrenheit, and its interesting, it seems that my heat pump at least, expects all the setpoints to still be in Celsius. So I think Homekit is doing the conversion in this case. I wonder if just having a setting to reduce the decimal place might fix the issue you are seeing.

**Comment by jonathangreen** [comment]
@danhvos I pushed up a new version of this plugin v1.1.0. It has a [new config option](https://github.com/jonathangreen/homebridge-fglair#installation) `temperature_unit`, if you set this to `fahrenheit`, I believe you should then see the values in homekit reflecting the values in the fglair app accurately. 

Let me know if this fixes the discrepancy for you!
